### ISSUE TITLE
handling multiple required commands "on-open"

### ISSUE THREAD

**Issue by hellt** [networklore/netrasp#6]
Hi,
currently the Dial procedure assumes a single `disablePager` command is required to prepare the session.
This seems a bit limiting. Some platforms do require several commands to prepare it for non-human driven CLI session. For example, to disable completion-on-space.

With that in mind it seems reasonable to pass a `onOpen()` function to the session preparation step where driver author can pack all that is needed to prepare the device.

**Comment by ogenstad** [comment]
Hm, I've viewed the establishConnection helper as a function for ios like devices and that it would be quite simple to implement something else in the Dial method for other drivers.

For your example I assume it would be enough to move from:

`func establishConnection(ctx context.Context, p Platform, c connection, prompt *regexp.Regexp, disablePager string) error {`

To the below and then just iterate over each preparationCommands and execute them one by one, or do you see anything more complex that's needed?

`func establishConnection(ctx context.Context, p Platform, c connection, prompt *regexp.Regexp, preparationCommands ...string) error {
`

**Comment by hellt** [comment]
yes, a in my case a list of commands will suffice
